name: 'fakerepo'
version: 2.0.1
description: A fake repo for testing

environment:
  sdk: '>=2.12.0 <3.0.0'

executables:
  release:

dependencies:
  github:
  yaml:

dependency_overrides:
  github:
    path: ../github.dart